### ISSUE TITLE
Error using larger cell numbers

### ISSUE THREAD

**Issue by vortexing** [KChen-lab/MonoVar#2]
I'm not sure you all are still messing with this tool but we thought I'd do a comparison using it.  We have more like 3,500+ cells and while everything executes when we have a handful of cells, when we run it on the full set we get this:
```
[mpileup] 3563 samples in 3563 input files
(mpileup) Max depth is above 1M. Potential memory hog!
Traceback (most recent call last):
  File "/src/monovar.py", line 158, in <module>
    nCr_matrix = U.Create_nCr_mat(max_allele_cnt, factorial_list)
  File "/src/utils.py", line 116, in Create_nCr_mat
    (factorial_list[i] * factorial_list[j - i])
OverflowError: long int too large to convert to float
```
I've hunted a bit and I could certainly imagine in your utils.py you could use a different module to create those large factorials but I'm not sure on first pass what the impact would be on the rest of the functions.  

This was supposed to be a somewhat quick comparison, so I thought I'd mention it in case someone more familiar with the code might be able to make a non-destructive adjustment faster than we can.  ;)

**Comment by vortexing** [comment]
I made some edits using the `decimal` module and it at least executes and doesn't appear to error out on anything else, but certainly I may have some unintended consequences.  We'll spot check it.

**Comment by acsala** [comment]
Hi @vortexing 

I am facing the same issue and geting the same error message upon applying monovar to ~600 cells.

Did your solution with the decimal module work out? And if so, could you share the solution?

Many thanks!

**Comment by vortexing** [comment]
It did end up working, BUT we decided monovar did not work for our datasets so we did not continue to explore it.  The working version I made is in this docker container if you have the ability to use docker: `fredhutch/monovar:1.2`.  Otherwise, the github repo is still private but I only made a wee change to `utils.py`.  Added `from decimal import Decimal` and then this:
```
    def Create_nCr_mat(self, max_allele_cnt, factorial_list):
        ncr_mat = np.zeros((max_allele_cnt, max_allele_cnt))
        for i in range(max_allele_cnt):
            for j in range(max_allele_cnt):
                ncr_mat[j, i] = Decimal( factorial_list[j] / \
                    (factorial_list[i] * factorial_list[j - i]) )
        return ncr_mat
```
Just added the `Decimal()` bit.
